-- ТЗ #031 Block 1: navesy pricing & specs schema
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS price_per_m2 NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS roof_shape TEXT,
  ADD COLUMN IF NOT EXISTS roof_material TEXT,
  ADD COLUMN IF NOT EXISTS min_area_m2 NUMERIC(6,2) DEFAULT 24;

COMMENT ON COLUMN products.price_per_m2 IS 'Цена за м² для navesy products (NULL для metalloprokat)';
COMMENT ON COLUMN products.roof_shape IS 'arochny | dvuskatny | odnoskatny | poluarchny | chetyrehskatny | ploskiy | konsolny';
COMMENT ON COLUMN products.roof_material IS 'profnastil | polikarbonat | metallocherepitsa';

CREATE INDEX IF NOT EXISTS idx_products_navesy_filter
  ON products (category_id, roof_shape, roof_material) WHERE price_per_m2 IS NOT NULL;
-- ТЗ #031 Block 1: Backfill navesy pricing/specs
-- Source: WINDSURF_TASK_031_navesy_ui_separate.md, slug-derived

UPDATE products SET
  price_per_m2 = v.price,
  roof_shape = v.shape,
  roof_material = v.material
FROM (VALUES
  ('archniy-naves-polikarbonat-bez-ferm', 6500, 'arochny', 'polikarbonat'),
  ('archniy-naves-polikarbonat-gorizont-usilenie', 6500, 'arochny', 'polikarbonat'),
  ('archniy-naves-polikarbonat-par-usilenie', 6500, 'arochny', 'polikarbonat'),
  ('avto-4skat-metallocherepitsa-arka', 7200, 'chetyrehskatny', 'metallocherepitsa'),
  ('avto-4skat-metallocherepitsa-bez-ferm', 7200, 'chetyrehskatny', 'metallocherepitsa'),
  ('avto-4skat-polikarbonat-bez-ferm', 7200, 'chetyrehskatny', 'polikarbonat'),
  ('avto-archniy-polikarbonat-bez-ferm', 7200, 'arochny', 'polikarbonat'),
  ('avto-archniy-polikarbonat-gor-usilenie', 7200, 'arochny', 'polikarbonat'),
  ('avto-archniy-polikarbonat-par-usilenie', 7200, 'arochny', 'polikarbonat'),
  ('avto-archniy-polikarbonat-treug-usilenie', 7200, 'arochny', 'polikarbonat'),
  ('avto-dvuskat-metallocherepitsa-arka', 7200, 'dvuskatny', 'metallocherepitsa'),
  ('avto-dvuskat-metallocherepitsa-par-usilenie', 7200, 'dvuskatny', 'metallocherepitsa'),
  ('avto-dvuskat-metallocherepitsa-treug-usilenie', 7200, 'dvuskatny', 'metallocherepitsa'),
  ('avto-dvuskat-polikarbonat-arka', 7200, 'dvuskatny', 'polikarbonat'),
  ('avto-dvuskat-polikarbonat-bez-ferm', 7200, 'dvuskatny', 'polikarbonat'),
  ('avto-dvuskat-polikarbonat-par-usilenie', 7200, 'dvuskatny', 'polikarbonat'),
  ('avto-dvuskat-polikarbonat-treug-usilenie', 7200, 'dvuskatny', 'polikarbonat'),
  ('avto-dvuskat-profnastil-arka', 7200, 'dvuskatny', 'profnastil'),
  ('avto-dvuskat-profnastil-par-usilenie', 7200, 'dvuskatny', 'profnastil'),
  ('avto-dvuskat-profnastil-treug-usilenie', 7200, 'dvuskatny', 'profnastil'),
  ('avto-odnoskat-metallocherepitsa-bez-ferm', 7200, 'odnoskatny', 'metallocherepitsa'),
  ('avto-odnoskat-metallocherepitsa-par-usilenie', 7200, 'odnoskatny', 'metallocherepitsa'),
  ('avto-odnoskat-metallocherepitsa-treug-usilenie', 7200, 'odnoskatny', 'metallocherepitsa'),
  ('avto-odnoskat-polikarbonat-bez-ferm', 7200, 'odnoskatny', 'polikarbonat'),
  ('avto-odnoskat-polikarbonat-par-usilenie', 7200, 'odnoskatny', 'polikarbonat'),
  ('avto-odnoskat-polikarbonat-treug-usilenie', 7200, 'odnoskatny', 'polikarbonat'),
  ('avto-odnoskat-profnastil-par-usilenie', 7200, 'odnoskatny', 'profnastil'),
  ('avto-odnoskat-profnastil-treug-usilenie', 7200, 'odnoskatny', 'profnastil'),
  ('avto-ploskiy-polikarbonat-bez-ferm', 7200, 'ploskiy', 'polikarbonat'),
  ('avto-ploskiy-polikarbonat-par-usilenie', 7200, 'ploskiy', 'polikarbonat'),
  ('avto-poluarch-polikarbonat-bez-ferm', 7200, 'poluarchny', 'polikarbonat'),
  ('avto-poluarch-polikarbonat-par-usilenie', 7200, 'poluarchny', 'polikarbonat'),
  ('avto-poluarch-polikarbonat-treug-usilenie', 7200, 'poluarchny', 'polikarbonat'),
  ('bes-4skat-metal-bez-ferm', 7500, 'chetyrehskatny', 'metallocherepitsa'),
  ('bes-4skat-metal-par', 7500, 'chetyrehskatny', 'metallocherepitsa'),
  ('bes-4skat-poli-par', 7500, 'chetyrehskatny', 'polikarbonat'),
  ('bes-arch-poli-bez-ferm', 7500, 'arochny', 'polikarbonat'),
  ('bes-arch-poli-par', 7500, 'arochny', 'polikarbonat'),
  ('bes-arch-poli-treug', 7500, 'arochny', 'polikarbonat'),
  ('bes-dvuskat-metal-bez-ferm', 7500, 'dvuskatny', 'metallocherepitsa'),
  ('bes-dvuskat-metal-par', 7500, 'dvuskatny', 'metallocherepitsa'),
  ('bes-dvuskat-metal-treug', 7500, 'dvuskatny', 'metallocherepitsa'),
  ('bes-dvuskat-poli-bez-ferm', 7500, 'dvuskatny', 'polikarbonat'),
  ('bes-dvuskat-poli-par', 7500, 'dvuskatny', 'polikarbonat'),
  ('bes-dvuskat-poli-treug', 7500, 'dvuskatny', 'polikarbonat'),
  ('bes-dvuskat-prof-bez-ferm', 7500, 'dvuskatny', 'profnastil'),
  ('bes-dvuskat-prof-par', 7500, 'dvuskatny', 'profnastil'),
  ('bes-dvuskat-prof-treug', 7500, 'dvuskatny', 'profnastil'),
  ('bes-odnoskat-metal-bez-ferm', 7500, 'odnoskatny', 'metallocherepitsa'),
  ('bes-odnoskat-metal-par', 7500, 'odnoskatny', 'metallocherepitsa'),
  ('bes-odnoskat-metal-treug', 7500, 'odnoskatny', 'metallocherepitsa'),
  ('bes-odnoskat-poli-bez-ferm', 7500, 'odnoskatny', 'polikarbonat'),
  ('bes-odnoskat-poli-par', 7500, 'odnoskatny', 'polikarbonat'),
  ('bes-odnoskat-prof-bez-ferm', 7500, 'odnoskatny', 'profnastil'),
  ('bes-odnoskat-prof-par', 7500, 'odnoskatny', 'profnastil'),
  ('bes-odnoskat-prof-treug', 7500, 'odnoskatny', 'profnastil'),
  ('bes-ploskiy-poli-bez-ferm', 7500, 'ploskiy', 'polikarbonat'),
  ('bes-poluarch-poli-bez-ferm', 7500, 'poluarchny', 'polikarbonat'),
  ('bes-poluarch-poli-par', 7500, 'poluarchny', 'polikarbonat'),
  ('chetyrehskatnyy-naves-metallocherepitsa-bez-ferm', 6500, 'chetyrehskatny', 'metallocherepitsa'),
  ('chetyrehskatnyy-naves-polikarbonat-bez-ferm', 6500, 'chetyrehskatny', 'polikarbonat'),
  ('dach-4skat-metal-bez-ferm', 7500, 'chetyrehskatny', 'metallocherepitsa'),
  ('dach-4skat-poli-bez-ferm', 6500, 'chetyrehskatny', 'polikarbonat'),
  ('dach-arch-poli-bez-ferm', 6500, 'arochny', 'polikarbonat'),
  ('dach-arch-poli-par', 6500, 'arochny', 'polikarbonat'),
  ('dach-arch-poli-treug', 6500, 'arochny', 'polikarbonat'),
  ('dach-dvuskat-metal-bez-ferm', 7500, 'dvuskatny', 'metallocherepitsa'),
  ('dach-dvuskat-metal-par', 7500, 'dvuskatny', 'metallocherepitsa'),
  ('dach-dvuskat-poli-bez-ferm', 6500, 'dvuskatny', 'polikarbonat'),
  ('dach-dvuskat-poli-par', 6500, 'dvuskatny', 'polikarbonat'),
  ('dach-dvuskat-poli-treug', 6500, 'dvuskatny', 'polikarbonat'),
  ('dach-dvuskat-prof-bez-ferm', 7200, 'dvuskatny', 'profnastil'),
  ('dach-dvuskat-prof-par', 7200, 'dvuskatny', 'profnastil'),
  ('dach-kons-metal-bez-ferm', 7500, 'konsolny', 'metallocherepitsa'),
  ('dach-kons-poli-bez-ferm', 6500, 'konsolny', 'polikarbonat'),
  ('dach-kons-prof-bez-ferm', 7200, 'konsolny', 'profnastil'),
  ('dach-odnoskat-metal-bez-ferm', 7500, 'odnoskatny', 'metallocherepitsa'),
  ('dach-odnoskat-metal-par', 7500, 'odnoskatny', 'metallocherepitsa'),
  ('dach-odnoskat-poli-bez-ferm', 6500, 'odnoskatny', 'polikarbonat'),
  ('dach-odnoskat-poli-par', 6500, 'odnoskatny', 'polikarbonat'),
  ('dach-odnoskat-poli-treug', 6500, 'odnoskatny', 'polikarbonat'),
  ('dach-odnoskat-prof-bez-ferm', 7200, 'odnoskatny', 'profnastil'),
  ('dach-odnoskat-prof-par', 7200, 'odnoskatny', 'profnastil'),
  ('dach-odnoskat-prof-treug', 7200, 'odnoskatny', 'profnastil'),
  ('dach-ploskiy-poli-bez-ferm', 6500, 'ploskiy', 'polikarbonat'),
  ('dach-poluarch-poli-bez-ferm', 6500, 'poluarchny', 'polikarbonat'),
  ('dach-poluarch-poli-par', 6500, 'poluarchny', 'polikarbonat'),
  ('dvuskatnyy-naves-metallocherepitsa-arka', 6500, 'dvuskatny', 'metallocherepitsa'),
  ('dvuskatnyy-naves-metallocherepitsa-par-usilenie', 6500, 'dvuskatny', 'metallocherepitsa'),
  ('dvuskatnyy-naves-metallocherepitsa-treug-usilenie', 6500, 'dvuskatny', 'metallocherepitsa'),
  ('dvuskatnyy-naves-polikarbonat-arka', 6500, 'dvuskatny', 'polikarbonat'),
  ('dvuskatnyy-naves-polikarbonat-par-usilenie', 6500, 'dvuskatny', 'polikarbonat'),
  ('dvuskatnyy-naves-polikarbonat-treug-usilenie', 6500, 'dvuskatny', 'polikarbonat'),
  ('dvuskatnyy-naves-profnastil-arka', 6500, 'dvuskatny', 'profnastil'),
  ('dvuskatnyy-naves-profnastil-par-usilenie', 6500, 'dvuskatny', 'profnastil'),
  ('dvuskatnyy-naves-profnastil-treug-usilenie', 6500, 'dvuskatny', 'profnastil'),
  ('odnoskatnyy-naves-metallocherepitsa-bez-ferm', 6500, 'odnoskatny', 'metallocherepitsa'),
  ('odnoskatnyy-naves-metallocherepitsa-par-usilenie', 6500, 'odnoskatny', 'metallocherepitsa'),
  ('odnoskatnyy-naves-metallocherepitsa-treug-usilenie', 6500, 'odnoskatny', 'metallocherepitsa'),
  ('odnoskatnyy-naves-polikarbonat-bez-ferm', 6500, 'odnoskatny', 'polikarbonat'),
  ('odnoskatnyy-naves-polikarbonat-par-usilenie', 6500, 'odnoskatny', 'polikarbonat'),
  ('odnoskatnyy-naves-polikarbonat-treug-usilenie', 6500, 'odnoskatny', 'polikarbonat'),
  ('odnoskatnyy-naves-profnastil-par-usilenie', 6500, 'odnoskatny', 'profnastil'),
  ('odnoskatnyy-naves-profnastil-treug-usilenie', 6500, 'odnoskatny', 'profnastil'),
  ('park2-4skat-metal-bez-ferm', 6500, 'chetyrehskatny', 'metallocherepitsa'),
  ('park2-4skat-poli-bez-ferm', 6500, 'chetyrehskatny', 'polikarbonat'),
  ('park2-arch-poli-bez-ferm', 6500, 'arochny', 'polikarbonat'),
  ('park2-arch-poli-gor', 6500, 'arochny', 'polikarbonat'),
  ('park2-arch-poli-par', 6500, 'arochny', 'polikarbonat'),
  ('park2-arch-poli-treug', 6500, 'arochny', 'polikarbonat'),
  ('park2-dvuskat-metal-bez-ferm', 6500, 'dvuskatny', 'metallocherepitsa'),
  ('park2-dvuskat-metal-par', 6500, 'dvuskatny', 'metallocherepitsa'),
  ('park2-dvuskat-metal-treug', 6500, 'dvuskatny', 'metallocherepitsa'),
  ('park2-dvuskat-poli-bez-ferm', 6500, 'dvuskatny', 'polikarbonat'),
  ('park2-dvuskat-poli-par', 6500, 'dvuskatny', 'polikarbonat'),
  ('park2-dvuskat-poli-treug', 6500, 'dvuskatny', 'polikarbonat'),
  ('park2-dvuskat-prof-bez-ferm', 6500, 'dvuskatny', 'profnastil'),
  ('park2-dvuskat-prof-par', 6500, 'dvuskatny', 'profnastil'),
  ('park2-dvuskat-prof-treug', 6500, 'dvuskatny', 'profnastil'),
  ('park2-kons-metal-bez-ferm', 6500, 'konsolny', 'metallocherepitsa'),
  ('park2-kons-poli-bez-ferm', 6500, 'konsolny', 'polikarbonat'),
  ('park2-kons-prof-bez-ferm', 6500, 'konsolny', 'profnastil'),
  ('park2-odnoskat-metal-bez-ferm', 6500, 'odnoskatny', 'metallocherepitsa'),
  ('park2-odnoskat-metal-par', 6500, 'odnoskatny', 'metallocherepitsa'),
  ('park2-odnoskat-metal-treug', 6500, 'odnoskatny', 'metallocherepitsa'),
  ('park2-odnoskat-poli-bez-ferm', 6500, 'odnoskatny', 'polikarbonat'),
  ('park2-odnoskat-poli-par', 6500, 'odnoskatny', 'polikarbonat'),
  ('park2-odnoskat-poli-treug', 6500, 'odnoskatny', 'polikarbonat'),
  ('park2-odnoskat-prof-bez-ferm', 6500, 'odnoskatny', 'profnastil'),
  ('park2-odnoskat-prof-par', 6500, 'odnoskatny', 'profnastil'),
  ('park2-odnoskat-prof-treug', 6500, 'odnoskatny', 'profnastil'),
  ('park2-ploskiy-poli-bez-ferm', 6500, 'ploskiy', 'polikarbonat'),
  ('park2-poluarch-poli-bez-ferm', 6500, 'poluarchny', 'polikarbonat'),
  ('park2-poluarch-poli-par', 6500, 'poluarchny', 'polikarbonat'),
  ('ploskiy-naves-polikarbonat-bez-ferm', 6500, 'ploskiy', 'polikarbonat'),
  ('poluarchniy-naves-polikarbonat-bez-ferm', 6500, 'poluarchny', 'polikarbonat'),
  ('poluarchniy-naves-polikarbonat-par-usilenie', 6500, 'poluarchny', 'polikarbonat')
) AS v(slug, price, shape, material)
WHERE products.slug = v.slug;
